# Generated by Django 4.1.5 on 2023-01-26 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_alter_socialprofile_avatar_postimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialProfile',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.post'),
        ),
    ]
