# Generated by Django 4.1.5 on 2023-02-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_followerrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerRelation',
        ),
    ]
