# Generated by Django 4.1.6 on 2023-02-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_postcomment_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='social.profile'),
        ),
    ]
