# Generated by Django 4.1.6 on 2023-02-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.profile'),
        ),
    ]
